import { WEATHER } from '../data/weather.js'
import { island } from '../data/world.js'
import { surfaceAt } from './heightfield.js'

/**
 * The island's soundtrack, synthesised.
 *
 * Everything here is generated by the Web Audio API at runtime: there is not a
 * single audio file in the build. That started as a licensing decision in phase
 * 4 — no free library exposes a machine-verifiable licence per file, and
 * shipping audio we can't attribute properly in CREDITS.md wasn't worth it —
 * and the ambience layer only makes the case stronger. Six cross-fading beds
 * plus four footstep surfaces would be a megabyte of downloads for sounds a few
 * lines of arithmetic produce, and the synthesised versions respond to the
 * world continuously: the surf really does get louder as you walk to the
 * shore, rather than switching between a "near" and a "far" file.
 *
 * Kept out of React deliberately. Audio.jsx is a dozen lines of glue; all the
 * state lives in the closure below, so nothing here can trigger a render.
 */

// ---------------------------------------------------------------- helpers ---

/** One second of brown noise — smoother and far less hissy than white. */
function brownNoise(ctx, seconds = 4) {
  const buffer = ctx.createBuffer(1, ctx.sampleRate * seconds, ctx.sampleRate)
  const data = buffer.getChannelData(0)
  let last = 0
  for (let i = 0; i < data.length; i++) {
    const white = Math.random() * 2 - 1
    last = (last + 0.02 * white) / 1.02
    data[i] = last * 3.5
  }
  return buffer
}

/** White noise, for footstep transients. */
function whiteNoise(ctx, seconds = 1) {
  const buffer = ctx.createBuffer(1, ctx.sampleRate * seconds, ctx.sampleRate)
  const data = buffer.getChannelData(0)
  for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1
  return buffer
}

/**
 * Crickets, baked into one looping buffer.
 *
 * Scheduling thousands of 11ms oscillator pulses through the graph would be
 * the obvious approach and would cost far more than it's worth; writing the
 * same pulses into six seconds of samples costs one pass at startup. Each
 * voice wraps around the end of the buffer, so the loop point is inaudible.
 */
function cricketBed(ctx, seconds = 6) {
  const buffer = ctx.createBuffer(1, ctx.sampleRate * seconds, ctx.sampleRate)
  const data = buffer.getChannelData(0)
  const rate = ctx.sampleRate

  for (let voice = 0; voice < 7; voice++) {
    const freq = 4200 + Math.random() * 900
    const every = 1.0 + Math.random() * 1.4
    const pulses = 5 + Math.floor(Math.random() * 4)
    const pulseLength = Math.floor(0.011 * rate)
    const gap = 0.028
    const level = 0.05 + Math.random() * 0.035

    for (let t = Math.random() * every; t < seconds; t += every) {
      for (let p = 0; p < pulses; p++) {
        const start = Math.floor((t + p * gap) * rate)
        for (let i = 0; i < pulseLength; i++) {
          const env = Math.sin((i / pulseLength) * Math.PI)
          data[(start + i) % data.length] +=
            Math.sin((2 * Math.PI * freq * i) / rate) * env * level
        }
      }
    }
  }
  return buffer
}

const clamp01 = (v) => Math.min(1, Math.max(0, v))
const smoothstep = (a, b, x) => {
  const t = clamp01((x - a) / (b - a))
  return t * t * (3 - 2 * t)
}

// ----------------------------------------------------------------- engine ---

/**
 * Footstep voicing per surface. The point of difference is the filter, not the
 * volume: grass is a mid-band rustle, the worn path is a duller thud, sand is a
 * long soft hiss with no attack at all, and rock is a short bright click.
 */
const FOOTSTEPS = {
  grass: { type: 'bandpass', frequency: 1700, Q: 0.8, decay: 0.1, level: 0.16, thud: 0.0 },
  dirt: { type: 'bandpass', frequency: 850, Q: 0.9, decay: 0.12, level: 0.2, thud: 0.35 },
  sand: { type: 'highpass', frequency: 2400, Q: 0.4, decay: 0.19, level: 0.13, thud: 0.0 },
  cliff: { type: 'highpass', frequency: 1900, Q: 1.4, decay: 0.07, level: 0.2, thud: 0.5 },
}

export function createAudioEngine() {
  const AudioContextClass = window.AudioContext || window.webkitAudioContext
  if (!AudioContextClass) return null

  const ctx = new AudioContextClass()
  const master = ctx.createGain()
  master.gain.value = 0
  master.connect(ctx.destination)
  // A bed that snaps on is startling.
  master.gain.linearRampToValueAtTime(0.5, ctx.currentTime + 2.2)

  const noise = { brown: brownNoise(ctx), white: whiteNoise(ctx) }
  const stops = []
  let disposed = false

  /** A named gain stage that can be eased toward a target from anywhere. */
  function layer(initial = 0) {
    const gain = ctx.createGain()
    gain.gain.value = initial
    gain.connect(master)
    return {
      node: gain,
      /**
       * setTargetAtTime rather than a value ramp on a ticker: the browser eases
       * it on the audio thread, so a long frame on the main thread can't turn a
       * cross-fade into a step.
       */
      to(value, seconds = 1.5) {
        if (disposed) return
        gain.gain.setTargetAtTime(value, ctx.currentTime, Math.max(0.01, seconds / 3))
      },
    }
  }

  /** Looping noise through a filter — the bed under everything. */
  function noiseLayer({ buffer, type, frequency, Q = 0.6, swellRate = 0, swellDepth = 0 }) {
    const out = layer(0)
    const source = ctx.createBufferSource()
    source.buffer = buffer
    source.loop = true

    const filter = ctx.createBiquadFilter()
    filter.type = type
    filter.frequency.value = frequency
    filter.Q.value = Q

    source.connect(filter).connect(out.node)
    source.start()
    stops.push(() => source.stop())

    if (swellRate) {
      // Modulating the filter rather than the gain is what makes a gust read as
      // moving air instead of someone turning a volume knob.
      const lfo = ctx.createOscillator()
      lfo.frequency.value = swellRate
      const depth = ctx.createGain()
      depth.gain.value = swellDepth
      lfo.connect(depth).connect(filter.frequency)
      lfo.start()
      stops.push(() => lfo.stop())
    }

    return out
  }

  // --- the beds ------------------------------------------------------------

  /** Surf. Always present, but its level is a function of where you're standing. */
  const surf = noiseLayer({
    buffer: noise.brown,
    type: 'lowpass',
    frequency: 420,
    swellRate: 0.06,
    swellDepth: 120,
  })

  /** Wind in the trees. Rises with the weather's `wind`. */
  const gusts = noiseLayer({
    buffer: noise.brown,
    type: 'bandpass',
    frequency: 700,
    Q: 0.35,
    swellRate: 0.17,
    swellDepth: 460,
  })

  const crickets = (() => {
    const out = layer(0)
    const source = ctx.createBufferSource()
    source.buffer = cricketBed(ctx)
    source.loop = true
    // Roll the top off so it sits behind the scene instead of in front of it.
    const filter = ctx.createBiquadFilter()
    filter.type = 'lowpass'
    filter.frequency.value = 6200
    source.connect(filter).connect(out.node)
    source.start()
    stops.push(() => source.stop())
    return out
  })()

  const birds = layer(0)
  birds.node.gain.value = 1 // birdsong level is carried by each chirp instead

  /** A quiet, slightly detuned drone in the key the chime resolves to. */
  const drone = (() => {
    const out = layer(0.055)
    for (const [freq, detune] of [
      [110, -4],
      [164.81, 5],
      [246.94, -7],
    ]) {
      const osc = ctx.createOscillator()
      osc.type = 'sine'
      osc.frequency.value = freq
      osc.detune.value = detune

      const voice = ctx.createGain()
      voice.gain.value = 0.34

      // Each voice drifts at its own rate so the chord never sits still.
      const lfo = ctx.createOscillator()
      lfo.frequency.value = 0.03 + Math.random() * 0.04
      const depth = ctx.createGain()
      depth.gain.value = 0.16
      lfo.connect(depth).connect(voice.gain)

      osc.connect(voice).connect(out.node)
      osc.start()
      lfo.start()
      stops.push(() => {
        osc.stop()
        lfo.stop()
      })
    }
    return out
  })()

  // --- birdsong ------------------------------------------------------------

  let birdPresence = 0
  let birdTimer = null

  /** Two to four notes, each a quick sweep up and back — a phrase, not a beep. */
  function chirp(level) {
    const start = ctx.currentTime
    const base = 2100 + Math.random() * 1400
    const notes = 2 + Math.floor(Math.random() * 3)

    for (let i = 0; i < notes; i++) {
      const t = start + i * (0.09 + Math.random() * 0.06)
      const f0 = base * (0.9 + Math.random() * 0.3)

      const osc = ctx.createOscillator()
      osc.type = 'sine'
      osc.frequency.setValueAtTime(f0, t)
      osc.frequency.exponentialRampToValueAtTime(f0 * (1.25 + Math.random() * 0.4), t + 0.035)
      osc.frequency.exponentialRampToValueAtTime(f0 * 0.92, t + 0.085)

      const env = ctx.createGain()
      env.gain.setValueAtTime(0, t)
      env.gain.linearRampToValueAtTime(level, t + 0.008)
      env.gain.exponentialRampToValueAtTime(0.0001, t + 0.11)

      osc.connect(env).connect(birds.node)
      osc.start(t)
      osc.stop(t + 0.13)
    }
  }

  /**
   * Scheduled one at a time rather than looped: birdsong is the one layer where
   * a repeat is obvious, because the ear tracks the phrase.
   */
  function scheduleBird() {
    if (disposed) return
    const wait = 1400 + Math.random() * 4600
    birdTimer = setTimeout(() => {
      if (birdPresence > 0.05) chirp(0.05 * birdPresence)
      scheduleBird()
    }, wait)
  }
  scheduleBird()

  // --- footsteps -----------------------------------------------------------

  let stepClock = 0
  let stepFoot = 0
  let surfClock = 0

  function footstep(surface) {
    const voice = FOOTSTEPS[surface] ?? FOOTSTEPS.grass
    const now = ctx.currentTime
    // Alternate feet: one a touch quieter and duller than the other, which is
    // what stops a run reading as a metronome.
    stepFoot ^= 1
    const trim = stepFoot ? 1 : 0.82

    const source = ctx.createBufferSource()
    source.buffer = noise.white
    source.playbackRate.value = 0.85 + Math.random() * 0.3
    // Start somewhere random in the buffer so no two steps are the same sample.
    const offset = Math.random() * (noise.white.duration - voice.decay - 0.05)

    const filter = ctx.createBiquadFilter()
    filter.type = voice.type
    filter.frequency.value = voice.frequency * (0.92 + Math.random() * 0.16)
    filter.Q.value = voice.Q

    const env = ctx.createGain()
    env.gain.setValueAtTime(0, now)
    env.gain.linearRampToValueAtTime(voice.level * trim, now + 0.006)
    env.gain.exponentialRampToValueAtTime(0.0001, now + voice.decay)

    source.connect(filter).connect(env).connect(master)
    source.start(now, offset, voice.decay + 0.05)

    // The body of the step: a short low thump under the rustle. Only the
    // surfaces that have something solid to strike get one.
    if (voice.thud > 0) {
      const osc = ctx.createOscillator()
      osc.type = 'sine'
      osc.frequency.setValueAtTime(110, now)
      osc.frequency.exponentialRampToValueAtTime(48, now + 0.07)
      const thump = ctx.createGain()
      thump.gain.setValueAtTime(0, now)
      thump.gain.linearRampToValueAtTime(0.07 * voice.thud * trim, now + 0.005)
      thump.gain.exponentialRampToValueAtTime(0.0001, now + 0.1)
      osc.connect(thump).connect(master)
      osc.start(now)
      osc.stop(now + 0.12)
    }
  }

  // --- public surface ------------------------------------------------------

  return {
    context: ctx,
    destination: master,

    /** Cross-fade the beds toward a weather preset. */
    setWeather(index) {
      const preset = WEATHER[index] ?? WEATHER[0]
      birdPresence = preset.birds
      // Rain has its own visual downpour but no sound of its own, so the gust
      // bed carries it — hence the deliberate over-weighting for wet presets.
      gusts.to(0.06 + preset.wind * 0.22, 4)
      crickets.to(preset.key === 'night' ? 0.55 : preset.key === 'sunset' ? 0.16 : 0, 5)
      drone.to(preset.key === 'night' ? 0.09 : 0.055, 5)
    },

    /**
     * Called once a frame with the player's position and motion.
     *
     * Two jobs: hold the surf at the level that matches the distance to the
     * water, and decide whether a foot has landed.
     */
    step(position, motion, delta, active) {
      if (disposed) return

      // Surf. Loudest at the waterline, never silent inland — you can always
      // hear the sea on an island this size. Retargeted a few times a second
      // rather than every frame: the easing happens on the audio thread, and
      // sixty scheduled events a second to describe a walking pace is waste.
      surfClock -= delta
      if (surfClock <= 0) {
        surfClock = 0.15
        const distance = Math.hypot(position.x, position.z)
        const nearShore = smoothstep(island.shoreRadius - 30, island.shoreRadius + 2, distance)
        surf.to(0.22 + nearShore * 0.62, 0.6)
      }

      if (!active || !motion.grounded || motion.speed < 0.6) {
        // Reset rather than pause, so the first step after stopping lands
        // immediately instead of after whatever was left on the clock.
        stepClock = 0
        return
      }

      stepClock -= delta
      if (stepClock > 0) return

      footstep(surfaceAt(position.x, position.z))
      // Cadence follows speed, which is also what drives the walk/run clips —
      // so the steps stay with the animation without reading its phase. The
      // few percent of jitter matters: the clock can only fire on a frame
      // boundary, so a fixed interval comes out perfectly quantised and starts
      // to sound like a drum machine rather than a person.
      const interval = Math.min(0.62, Math.max(0.2, 1.15 / motion.speed))
      stepClock = interval * (0.94 + Math.random() * 0.12)
    },

    /**
     * Picking up a spark: two notes, up.
     *
     * The pitch climbs a scale degree with each one found, so the twelfth
     * sounds an octave above the first and the set audibly fills up. That's the
     * whole reason this takes the count — a fixed pickup sound tells you
     * something happened, a rising one tells you how far along you are.
     */
    pickup(index = 0) {
      if (disposed) return
      const now = ctx.currentTime
      // Major pentatonic, so any two in a row are consonant however you
      // stumble across them.
      const steps = [0, 2, 4, 7, 9]
      const semis = steps[index % steps.length] + 12 * Math.floor(index / steps.length)
      const root = 587.33 * Math.pow(2, semis / 12) // D5 up

      for (const [mult, delay, level] of [
        [1, 0, 0.13],
        [1.5, 0.085, 0.1],
      ]) {
        const osc = ctx.createOscillator()
        osc.type = 'triangle'
        osc.frequency.value = root * mult

        const env = ctx.createGain()
        env.gain.setValueAtTime(0, now + delay)
        env.gain.linearRampToValueAtTime(level, now + delay + 0.01)
        env.gain.exponentialRampToValueAtTime(0.0001, now + delay + 0.55)

        osc.connect(env).connect(master)
        osc.start(now + delay)
        osc.stop(now + delay + 0.6)
      }
    },

    /** All twelve found: a short rising figure, once. */
    fanfare() {
      if (disposed) return
      const now = ctx.currentTime
      const notes = [587.33, 739.99, 880, 1174.66]
      notes.forEach((freq, i) => {
        const t = now + i * 0.13
        for (const [mult, level] of [
          [1, 0.12],
          [2, 0.05],
        ]) {
          const osc = ctx.createOscillator()
          osc.type = 'triangle'
          osc.frequency.value = freq * mult
          const env = ctx.createGain()
          env.gain.setValueAtTime(0, t)
          env.gain.linearRampToValueAtTime(level, t + 0.012)
          env.gain.exponentialRampToValueAtTime(0.0001, t + (i === notes.length - 1 ? 2.2 : 0.7))
          osc.connect(env).connect(master)
          osc.start(t)
          osc.stop(t + 2.4)
        }
      })
    },

    /** A soft bell, struck when a zone fans its cards out. */
    chime() {
      if (disposed) return
      const now = ctx.currentTime
      for (const [freq, delay, level] of [
        [880, 0, 0.16],
        [1318.5, 0.07, 0.1],
        [1760, 0.13, 0.05],
      ]) {
        const osc = ctx.createOscillator()
        osc.type = 'sine'
        osc.frequency.value = freq

        const env = ctx.createGain()
        env.gain.setValueAtTime(0, now + delay)
        env.gain.linearRampToValueAtTime(level, now + delay + 0.012)
        env.gain.exponentialRampToValueAtTime(0.0001, now + delay + 1.5)

        osc.connect(env).connect(master)
        osc.start(now + delay)
        osc.stop(now + delay + 1.6)
      }
    },

    dispose() {
      if (disposed) return
      disposed = true
      clearTimeout(birdTimer)
      for (const stop of stops) {
        try {
          stop()
        } catch {
          // Already stopped — a source that ended on its own throws here.
        }
      }
      ctx.close()
    },
  }
}
